name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build image
      run: |
        cd MelindaW-P1/PlainOldStoreApp.Ui/PlainOldStoreApp.Ui/
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/posaui
        
    - name: Push to DuckerHub
      run: |
        docker login - u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} docker.io
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/posaui
