name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd PlainOldStoreApp.Ui/
        docker build . --file Dockerfile --tag posaconsoleapp

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Push to DockerHub
      run: docker push posaconsoleapp
